# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4300fb1708b369b4083dd5032f2829be0f1977aeffdafe7ac6519d938cd70e2a223871a5cc84fbfcdb80764fc1e69a86783b394c35a14a00f584511d020dbf76

test:
  secret_key_base: 3791403f7da2c4e186954d35c1b8c59f8ed6a0fd72532e8429c561d19d86836609cf74095b406644d06310f00e0663de70e7b8316f17f91a29e2ce71d652a4aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
